import numpy as np
import config
from typing import Union


def magnetic_dipole_field(m, r, mu_0=4e-7 * np.pi):
    """
    Compute magnetic field generated by a magnetic dipole.

    Parameters
    ----------
    m : array-like, shape (3,)
        Magnetic dipole moment.
    r : array-like, shape (3,)
        Position vector from dipole to observation point.
    mu_0 : float
        Vacuum permeability.

    Returns
    -------
    B : ndarray, shape (3,)
        Magnetic flux density at position r.
    """
    m = np.asarray(m, dtype=np.float64).reshape(3, 1)
    r = np.asarray(r, dtype=np.float64).reshape(3, 1)

    r_norm = np.linalg.norm(r)
    if r_norm < 1e-15:
        return np.zeros(3)

    r_norm_3 = r_norm ** 3
    r_norm_5 = r_norm ** 5

    m_dot_r = float(m.T @ r)

    term1 = (3.0 * m_dot_r / r_norm_5) * r
    term2 = m / r_norm_3

    B = (mu_0 / (4.0 * np.pi)) * (term1 - term2)
    return B.flatten()


def magnetic_flux_3axis(
    sensor_position: Union[list, np.ndarray],
    grid_vec: np.ndarray,
    grid_positions: np.ndarray,
) -> np.ndarray:
    """
    Compute 3-axis magnetic flux density at sensor position.

    Parameters
    ----------
    sensor_position : array-like, shape (3,)
        Position of magnetic sensor.
    grid_vec : ndarray
        Deformation vectors of elastomer grid.
    grid_positions : ndarray
        Original grid positions.

    Returns
    -------
    b_sensor : ndarray, shape (3,)
        Magnetic flux density at sensor.
    """
    sensor_position = np.asarray(sensor_position, dtype=float).reshape(3)

    elastomer_positions = get_elastomer_positions(grid_vec, grid_positions)

    m = np.array([0.0, 0.0, config.B0], dtype=float)

    b_sensor = np.zeros(3, dtype=np.float64)

    gx, gy, gz = (
        config.GRID_SIZE[0],
        config.GRID_SIZE[1],
        config.GRID_SIZE[2] - 1,
    )

    for i in range(gx):
        for j in range(gy):
            for k in range(gz):
                r_vec = elastomer_positions[i, j, k] - sensor_position
                b_sensor += magnetic_dipole_field(m, r_vec)

    return b_sensor


def get_ref_positions(ref: Union[list, np.ndarray], grid_positions: np.ndarray) -> np.ndarray:
    """
    Apply reference offset to grid positions.
    """
    ref = np.asarray(ref, dtype=float).reshape(3)
    return grid_positions + ref


def get_elastomer_positions(
    grid_vec: np.ndarray, grid_positions: np.ndarray
) -> np.ndarray:
    """
    Compute deformed elastomer positions.
    """
    return grid_positions + grid_vec


def get_grid_positions() -> np.ndarray:
    """
    Generate regular 3D grid positions for elastomer.
    """
    gx, gy, gz = (
        config.GRID_SIZE[0],
        config.GRID_SIZE[1],
        config.GRID_SIZE[2] - 1,
    )

    grid_positions = np.zeros((gx, gy, gz, 3), dtype=float)

    i_coords = (np.arange(gx) - (gx - 1) / 2) * config.GRID_SPACING
    j_coords = (np.arange(gy) - (gy - 1) / 2) * config.GRID_SPACING
    k_coords = np.arange(1, gz + 1) * config.GRID_SPACING

    I, J, K = np.meshgrid(i_coords, j_coords, k_coords, indexing="ij")

    grid_positions[..., 0] = I
    grid_positions[..., 1] = J
    grid_positions[..., 2] = K

    return grid_positions


def magnetic_flux_3axis_vectorized(
    sensor_position: Union[list, np.ndarray],
    grid_vec: np.ndarray,
    grid_positions: np.ndarray,
) -> np.ndarray:
    """
    Fully vectorized magnetic flux computation.
    """
    sensor_position = np.asarray(sensor_position, dtype=float).reshape(1, 1, 1, 3)

    elastomer_positions = get_elastomer_positions(grid_vec, grid_positions)
    r_vectors = elastomer_positions - sensor_position

    r_norms = np.linalg.norm(r_vectors, axis=3, keepdims=True)
    r_norms = np.where(r_norms < 1e-15, np.inf, r_norms)

    m = np.array([0.0, 0.0, config.B0], dtype=float).reshape(1, 1, 1, 3)

    m_dot_r = np.sum(m * r_vectors, axis=3, keepdims=True)

    r_norm_3 = r_norms ** 3
    r_norm_5 = r_norms ** 5

    term1 = (3.0 * m_dot_r / r_norm_5) * r_vectors
    term2 = m / r_norm_3

    mu_0_4pi = 1e-7
    B_all = mu_0_4pi * (term1 - term2)

    return np.sum(B_all, axis=(0, 1, 2))


def compute_sensor_baseline(runner) -> np.ndarray:
    """
    Compute magnetic baseline for all sensors.

    The baseline corresponds to the magnetic field measured
    before deformation (or at the initial reference state).

    Parameters
    ----------
    runner : Simulatior
        Simulation runner containing grid deformation and positions.

    Returns
    -------
    baseline : ndarray, shape (SENSOR_NUMBER, 3)
        Baseline magnetic field for each sensor.
    """
    baseline = np.zeros((config.SENSOR_NUMBER, 3), dtype=np.float64)

    for i, sensor_pos in enumerate(config.SENSOR_ARRAY):
        baseline[i] = magnetic_flux_3axis(
            sensor_pos, runner.grid_vec, runner.grid_pos
        )

    return baseline


def get_magnetic_data(runner, baseline: np.ndarray) -> np.ndarray:
    """
    Compute magnetic field variation relative to baseline.

    Parameters
    ----------
    runner : Simulatior
        Simulation runner containing current grid deformation.
    baseline : ndarray, shape (SENSOR_NUMBER, 3)
        Pre-computed baseline magnetic field.

    Returns
    -------
    mag_data : ndarray, shape (SENSOR_NUMBER, 3)
        Differential magnetic field at each sensor.
    """
    mag_data = np.zeros((config.SENSOR_NUMBER, 3), dtype=np.float64)

    for i, sensor_pos in enumerate(config.SENSOR_ARRAY):
        mag_data[i] = (
            magnetic_flux_3axis(sensor_pos, runner.grid_vec, runner.grid_pos)
            - baseline[i]
        )

    return mag_data

