# config.py
import datetime

# 模拟参数
GRID_SIZE = (11, 11, 4)
INDENTER_RADIUS = 0.05
SIMULATION_DURATION = 3.0
MOVEMENT_SPEED = 1e-7
TIMESTEP = 1e-5

# 截图参数
SCREENSHOT_INTERVAL = 1000
SCREENSHOT_WIDTH = 1920
SCREENSHOT_HEIGHT = 1080
SCREENSHOT_QUALITY = 100

# 视频参数
VIDEO_FPS = 100
DELETE_FRAMES_AFTER_VIDEO = False

# 物理参数
FLEXCOMP_MASS_MULTIPLIER = 2e-4
INDENTER_DENSITY = 1000
JOINT_DAMPING = 100
JOINT_STIFFNESS = 5
INDENTER_LIMIT_L = 0.015
INDENTER_LIMIT_H = 0.035

INDENTER_X = 0
INDENTER_Y = 0
GRID_SPACING = 0.01

# 文件路径
MODEL_OUTPUT_FILE = "model/dynamic_model.xml"
DATA_DIR = "data"