# config.py
import platform

# 模拟参数
GRID_SIZE = (17, 17, 4)
INDENTER_RADIUS = 0.05
SIMULATION_DURATION = 3.0
MOVEMENT_SPEED = 0.01
TIMESTEP = 2e-4

# 截图参数
SCREENSHOT_FREQUENCY = 0.01  # 每0.01秒截图一次
SCREENSHOT_INTERVAL = int(SCREENSHOT_FREQUENCY / TIMESTEP)
SCREENSHOT_WIDTH = 1920
SCREENSHOT_HEIGHT = 1080
SCREENSHOT_QUALITY = 100

# 视频参数
VIDEO_FPS = 100
DELETE_FRAMES_AFTER_VIDEO = True

# 物理参数
GRID_SPACING = 0.01
FLEXCOMP_MASS_MULTIPLIER = 2*GRID_SPACING* GRID_SPACING 
INDENTER_DENSITY = 1000
JOINT_DAMPING = 1
JOINT_STIFFNESS = 0
INDENTER_LIMIT_L = 0.015
INDENTER_LIMIT_H = 0.035

INDENTER_X = 0
INDENTER_Y = 0

SENSOR_NUMBER = 5
SENSOR_ARRAY = [[0.04,0.04,0],[-0.04,0.04,0],[0.04,-0.04,0],[-0.04,-0.04,0],[0,0,0]]
MU0 = 1e-8
B0 = 1

EARLY_STOP_FLAG = True
TARGET_POSITION = 0.016
# 文件路径
MODEL_OUTPUT_FILE = "model/dynamic_model.xml"
DATA_DIR = "data"
SCREENSHOT_DIR = "data"

if platform.system() == "Windows":
    FFMPEG_PATH = r"C:\Users\admin\AppData\Local\ffmpeg\bin\ffmpeg.exe"  # 修改为你的实际路径
else:
    FFMPEG_PATH = "ffmpeg"